In [2]:
import numpy as n 
import pandas as p 
import matplotlib as m 
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [3]:
#dataset
iris = load_iris()
X = iris.data
y = iris.target 

In [4]:
X #features 

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
y #outputs 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
df = p.DataFrame(data=X , columns=iris.feature_names) 

In [10]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [11]:
df['target'] = y

In [13]:
df['target']

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int32

In [14]:
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size=0.2, random_state=12)


In [18]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_train

array([[-9.23010404e-01,  9.92828352e-01, -1.37449891e+00,
        -1.19654889e+00],
       [-4.32373645e-01, -1.45676683e+00, -5.72707879e-02,
        -2.75283018e-01],
       [ 5.48899875e-01, -3.43314477e-01,  1.03087418e+00,
         7.77592269e-01],
       [-4.32373645e-01,  2.55166165e+00, -1.37449891e+00,
        -1.32815830e+00],
       [-6.43960747e-02, -7.88695420e-01,  7.44520243e-01,
         9.09201679e-01],
       [-1.87055265e-01,  2.99704259e+00, -1.31722812e+00,
        -1.06493948e+00],
       [-3.09714455e-01, -3.43314477e-01, -1.14541576e-01,
         1.19545215e-01],
       [-4.32373645e-01, -1.45676683e+00, -8.77999358e-17,
        -1.43673607e-01],
       [-6.43960747e-02,  2.10628071e+00, -1.48904049e+00,
        -1.32815830e+00],
       [ 1.80922305e-01, -1.90214778e+00,  1.14541576e-01,
        -2.75283018e-01],
       [-9.23010404e-01, -1.23407636e+00, -4.58166303e-01,
        -1.43673607e-01],
       [-1.04566959e+00,  7.70137880e-01, -1.25995733e+00,
      

In [19]:
X_test

array([[5. , 3.5, 1.3, 0.3],
       [6.3, 2.5, 5. , 1.9],
       [4.4, 3. , 1.3, 0.2],
       [5.7, 2.8, 4.1, 1.3],
       [6.8, 3.2, 5.9, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [6.2, 3.4, 5.4, 2.3],
       [5.1, 3.4, 1.5, 0.2],
       [7.7, 3. , 6.1, 2.3],
       [5.1, 3.3, 1.7, 0.5],
       [5.6, 3. , 4.5, 1.5],
       [5.4, 3.9, 1.3, 0.4],
       [5.4, 3.4, 1.5, 0.4],
       [5.1, 3.7, 1.5, 0.4],
       [7. , 3.2, 4.7, 1.4],
       [7.2, 3.2, 6. , 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [5.9, 3. , 4.2, 1.5],
       [4.6, 3.4, 1.4, 0.3],
       [6.3, 2.5, 4.9, 1.5],
       [4.9, 3. , 1.4, 0.2],
       [6.1, 2.8, 4. , 1.3],
       [6.2, 2.8, 4.8, 1.8],
       [6. , 2.9, 4.5, 1.5],
       [4.8, 3.4, 1.9, 0.2],
       [6.7, 3. , 5.2, 2.3],
       [6.7, 3. , 5. , 1.7],
       [5.5, 2.6, 4.4, 1.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.5, 2.3, 1.3, 0.3]])

In [21]:
X_test = scaler.transform(X_test)
X_test

array([[5. , 3.5, 1.3, 0.3],
       [6.3, 2.5, 5. , 1.9],
       [4.4, 3. , 1.3, 0.2],
       [5.7, 2.8, 4.1, 1.3],
       [6.8, 3.2, 5.9, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [6.2, 3.4, 5.4, 2.3],
       [5.1, 3.4, 1.5, 0.2],
       [7.7, 3. , 6.1, 2.3],
       [5.1, 3.3, 1.7, 0.5],
       [5.6, 3. , 4.5, 1.5],
       [5.4, 3.9, 1.3, 0.4],
       [5.4, 3.4, 1.5, 0.4],
       [5.1, 3.7, 1.5, 0.4],
       [7. , 3.2, 4.7, 1.4],
       [7.2, 3.2, 6. , 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [5.9, 3. , 4.2, 1.5],
       [4.6, 3.4, 1.4, 0.3],
       [6.3, 2.5, 4.9, 1.5],
       [4.9, 3. , 1.4, 0.2],
       [6.1, 2.8, 4. , 1.3],
       [6.2, 2.8, 4.8, 1.8],
       [6. , 2.9, 4.5, 1.5],
       [4.8, 3.4, 1.9, 0.2],
       [6.7, 3. , 5.2, 2.3],
       [6.7, 3. , 5. , 1.7],
       [5.5, 2.6, 4.4, 1.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.5, 2.3, 1.3, 0.3]])

In [28]:
knn = KNeighborsClassifier(n_neighbors=3)

knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

accuracy = accuracy_score(y_test , y_pred )
print(f'accuracy: {accuracy * 100:.2f}%')

accuracy: 30.00%
